/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.proyectobancobda;

import com.itson.proyectobancobdapersistencia.conexion.IConexion;
import com.itson.proyectobancobdapersistencia.daos.CuentasDAO;
import com.itson.proyectobancobdapersistencia.daos.IClientesDAO;
import com.itson.proyectobancobdapersistencia.daos.ICuentasDAO;
import com.itson.proyectobancobdapersistencia.dtos.CuentaDTO;
import com.itson.proyectobancobdapersistencia.excepciones.PersistenciaException;
import com.itson.proyectobancobdapersistencia.excepciones.ValidacionDTOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gamaliel
 */
public class CuentaNuevaForm extends javax.swing.JFrame {

    /**
     * Creates new form CuentaNuevaForm
     */
    
    private final IClientesDAO clientesDAO;    
    private final ICuentasDAO cuentasDAO; 
    
    public CuentaNuevaForm(IClientesDAO clientesDAO, ICuentasDAO cuentasDAO) {      
        initComponents();
        this.cuentasDAO = cuentasDAO; 
        this.clientesDAO = clientesDAO ; 
    }

    private void generarCuentaAleatoria(){
        Random random = new Random();
        StringBuilder sb = new StringBuilder("4169");
        while (sb.length() < 16) {
            sb.append(random.nextInt(10));
        }
        String numCuenta = sb.toString();
        lblNumeroCuenta.setText(numCuenta);
    }
    
    private long obtenerIdCliente() {
        // Obtener el nombre, apellido paterno y apellido materno del cliente a actualizar
        String correo = txtCorreo.getText();

        // Obtener el ID del cliente a actualizar de la base de datos
        long idCliente = 0;
        try {
            idCliente = clientesDAO.obtenerIdCliente(correo);
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        return idCliente;
    }    

    
    private void crearCuentaNueva() throws ValidacionDTOException {
        long idCliente = obtenerIdCliente();

        if (this.cuentasDAO == null) {
            throw new NullPointerException("El atributo 'cuentasDAO' es null");
            
        } else{
            if (idCliente != -1) {
                String numCuenta = lblNumeroCuenta.getText();
                Double saldo = Double.valueOf(txtSaldoPesos.getText());

                LocalDate fechaActual = LocalDate.now();
                Date fechaAperturaActual = Date.valueOf(fechaActual);
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

                String fechaApertura = formatter.format(fechaAperturaActual);

                CuentaDTO cuentaNueva = new CuentaDTO();

                cuentaNueva.setNumCuenta(numCuenta);
                cuentaNueva.setSaldoPesos(saldo);
                cuentaNueva.setFechaApertura(fechaApertura);
                cuentaNueva.setIdCliente(idCliente);

                try {
                    cuentaNueva.esValido();
                    this.cuentasDAO.agregar(cuentaNueva);
                    JOptionPane.showMessageDialog(this, "Cuenta creada exitósamente.");
                } catch (PersistenciaException ex) {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al crear la cuenta.", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE);
                    System.err.println("Error: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }                
        }       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNumeroCuenta = new javax.swing.JLabel();
        btnCrear = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtSaldoPesos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Numero cuenta");

        lblNumeroCuenta.setText("jLabel2");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");

        txtSaldoPesos.setText("jTextField1");

        txtCorreo.setText("jTextField1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(204, 204, 204)
                            .addComponent(lblNumeroCuenta)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRegresar)
                            .addGap(107, 107, 107)
                            .addComponent(btnGenerar)
                            .addGap(116, 116, 116)
                            .addComponent(btnCrear)
                            .addGap(96, 96, 96)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSaldoPesos, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(txtCorreo))
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblNumeroCuenta))
                .addGap(54, 54, 54)
                .addComponent(txtSaldoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnGenerar)
                    .addComponent(btnRegresar))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        generarCuentaAleatoria();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            crearCuentaNueva();
        } catch (ValidacionDTOException ex) {
            Logger.getLogger(CuentaNuevaForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al crear la cuenta.", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);                    
        }
    }//GEN-LAST:event_btnCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtSaldoPesos;
    // End of variables declaration//GEN-END:variables
}
