/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.proyectobancobda;

import com.itson.proyectobancobdadominio.Cliente;
import com.itson.proyectobancobdapersistencia.daos.IClientesDAO;
import com.itson.proyectobancobdapersistencia.daos.ICuentasDAO;
import com.itson.proyectobancobdapersistencia.dtos.CuentaDTO;
import com.itson.proyectobancobdapersistencia.excepciones.PersistenciaException;
import com.itson.proyectobancobdapersistencia.excepciones.ValidacionDTOException;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gamaliel
 */
public class CuentaNuevaForm extends javax.swing.JFrame {

    /**
     * Creates new form CuentaNuevaForm
     */
    
    private final IClientesDAO clientesDAO;    
    private final ICuentasDAO cuentasDAO; 
    
    public CuentaNuevaForm(IClientesDAO clientesDAO, ICuentasDAO cuentasDAO) {      
        initComponents();
        this.clientesDAO = clientesDAO ; 
        this.cuentasDAO = cuentasDAO; 
    }

    private void generarCuentaAleatoria(){
        Random random = new Random();
        StringBuilder sb = new StringBuilder("4169");
        while (sb.length() < 16) {
            sb.append(random.nextInt(10));
        }
        String numCuenta = sb.toString();
        lblNumeroCuenta.setText(numCuenta);
    }
    
    private long obtenerIdCliente() {
        // Obtener el nombre, apellido paterno y apellido materno del cliente a actualizar
        String correo = txtCorreo.getText();

        // Obtener el ID del cliente a actualizar de la base de datos
        long idCliente = 0;
        try {
            idCliente = clientesDAO.obtenerIdCliente(correo);
        } catch (PersistenciaException e) {
            JOptionPane.showMessageDialog(this, "Error al obtener el ID del cliente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        return idCliente;
    }    

    
    private void crearCuentaNueva() throws ValidacionDTOException {
        long idCliente = obtenerIdCliente();

        if (this.cuentasDAO == null) {
            throw new NullPointerException("El atributo 'cuentasDAO' es null");
            
        } else{
            if (idCliente != -1) {
                String numCuenta = lblNumeroCuenta.getText();
                Double saldo = Double.valueOf(txtSaldoPesos.getText());

                LocalDate fechaActual = LocalDate.now();
                Date fechaAperturaActual = Date.valueOf(fechaActual);
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

                String fechaApertura = formatter.format(fechaAperturaActual);

                CuentaDTO cuentaNueva = new CuentaDTO();

                cuentaNueva.setNumCuenta(numCuenta);
                cuentaNueva.setSaldoPesos(saldo);
                cuentaNueva.setFechaApertura(fechaApertura);
                cuentaNueva.setIdCliente(idCliente);

                try {
                    cuentaNueva.esValido();
                    this.cuentasDAO.agregar(cuentaNueva);
                    JOptionPane.showMessageDialog(this, "Cuenta creada exitósamente.");
                } catch (PersistenciaException ex) {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al crear la cuenta.", 
                            "Error", 
                            JOptionPane.ERROR_MESSAGE);
                    System.err.println("Error: " + ex.getMessage());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.", "Error", JOptionPane.ERROR_MESSAGE);
            }                
        }       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNumeroCuenta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSaldoPesos = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(157, 36, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(98, 17, 50));

        jLabel3.setFont(new java.awt.Font("NATS", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BANCO DEL BIENESTAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 808, -1));

        btnRegresar.setBackground(new java.awt.Color(98, 17, 50));
        btnRegresar.setFont(new java.awt.Font("NATS", 1, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 120, -1));

        btnGenerar.setBackground(new java.awt.Color(179, 142, 93));
        btnGenerar.setFont(new java.awt.Font("NATS", 1, 24)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar");
        btnGenerar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGenerar.setBorderPainted(false);
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, 120, -1));

        btnCrear.setBackground(new java.awt.Color(40, 92, 77));
        btnCrear.setFont(new java.awt.Font("NATS", 1, 24)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear");
        btnCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrear.setBorderPainted(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 120, -1));

        jPanel3.setBackground(new java.awt.Color(157, 36, 73));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(179, 142, 93), 4));

        lblNumeroCuenta.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        lblNumeroCuenta.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroCuenta.setText("XXXXXXXXXXXXXXXX");

        jLabel5.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero de cuenta");

        jLabel4.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingresa correo para validar");

        txtSaldoPesos.setBackground(new java.awt.Color(157, 36, 73));
        txtSaldoPesos.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        txtSaldoPesos.setForeground(new java.awt.Color(255, 255, 255));
        txtSaldoPesos.setText("0.00");
        txtSaldoPesos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        txtCorreo.setBackground(new java.awt.Color(157, 36, 73));
        txtCorreo.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtCorreo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jLabel6.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Saldo a iniciar");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("________________________________");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("________________________________");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lblNumeroCuenta))
                    .addComponent(txtSaldoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroCuenta)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSaldoPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 550, 290));

        jLabel2.setFont(new java.awt.Font("NATS", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CREAR CUENTA BANCARIA");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        generarCuentaAleatoria();
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        try {
            crearCuentaNueva();
        } catch (ValidacionDTOException ex) {
            Logger.getLogger(CuentaNuevaForm.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error al crear la cuenta.", 
                        "Error", 
                        JOptionPane.ERROR_MESSAGE);                    
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        MisCuentasForm misCuentas = new MisCuentasForm(clientesDAO, cuentasDAO);
        misCuentas.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblNumeroCuenta;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtSaldoPesos;
    // End of variables declaration//GEN-END:variables
}
