package com.itson.proyectobancobda;


import com.itson.proyectobancobda.MenuPrincipalForm;
import com.itson.proyectobancobdadominio.Cliente;
import com.itson.proyectobancobdapersistencia.conexion.IConexion;
import com.itson.proyectobancobdapersistencia.daos.CuentasDAO;
import com.itson.proyectobancobdapersistencia.daos.IClientesDAO;
import com.itson.proyectobancobdapersistencia.daos.ICuentasDAO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gamaliel
 */
public class MenuClienteForm extends javax.swing.JFrame {

    private final IClientesDAO clientesDAO;
    private final ICuentasDAO cuentasDAO;
    private final IConexion conexion;
    private final Cliente cliente;
    /**
     * Creates new form MenuClienteForm
     */

    public MenuClienteForm(IClientesDAO clientesDAO, ICuentasDAO cuentasDAO, Cliente cliente, IConexion conexion) {
        initComponents();
        this.clientesDAO = clientesDAO;
        this.cuentasDAO = cuentasDAO;
        this.cliente = cliente;
        this.conexion =conexion;
        lblInicioMenuCliente.setText("Bienvenid@ "+cliente.getNombre());
    }

    private void crearCuenta(){

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInicioMenuCliente = new javax.swing.JLabel();
        btnCrearCuenta = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnAñadirSaldo = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnRetiroSinTarjeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblInicioMenuCliente.setText("jLabel1");

        btnCrearCuenta.setText("Crear cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar datos");

        btnAñadirSaldo.setText("Añadir Saldo");

        btnTransferencia.setText("Transferencia");

        btnRetiroSinTarjeta.setText("Retiro sin tarjeta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(btnCrearCuenta)
                .addGap(90, 90, 90)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btnAñadirSaldo)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblInicioMenuCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTransferencia)
                .addGap(128, 128, 128)
                .addComponent(btnRetiroSinTarjeta)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblInicioMenuCliente)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrearCuenta)
                            .addComponent(btnActualizar)
                            .addComponent(btnAñadirSaldo))
                        .addGap(64, 242, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRetiroSinTarjeta)
                            .addComponent(btnTransferencia))
                        .addGap(81, 81, 81))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        this.setVisible(false);
        MisCuentasForm menuPrincipal = new MisCuentasForm();
        menuPrincipal.setVisible(true);
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAñadirSaldo;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton btnRetiroSinTarjeta;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel lblInicioMenuCliente;
    // End of variables declaration//GEN-END:variables
}
